esphome:
  name: espuart
  friendly_name: espuart

esp8266:
  board: esp01_1m

logger:
  level: DEBUG

api:
  encryption:
    key: "KEY"

ota:
  password: "STRONK_PASSWORD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Espuart Fallback Hotspot"
    password: "STRONK_PASSWORD"

uart:
  baud_rate: 9600
  tx_pin: 1
  rx_pin: 3
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);
